#!/usr/bin/env bash

# For Django: run manage.py in either the project or app level
function m(){
    (
        while true; do
            if [[ -f manage.py ]]; then
                python manage.py "$@"

                return 0
            else
                if [[ $(pwd) = '/' ]]; then
                    echo "Cannot find manage.py."
                    return 1
                fi
                
                cd ..
            fi
        done
    )
}
