#!/usr/bin/env bash

# Easily clone GitHub repos: gh-clone <user> <repo> [<clone-path>]
function gh-clone(){
    git clone "git@github.com:$1/$2.git" $3
}

# Easily clone BitBucket repos: bb-clone <user> <repo> [<clone-path>]
function bb-clone(){
    git clone "git@bitbucket.com:$1/$2.git" $3
}
