#!/usr/bin/env bash

smancache=$HOME/.dotfiles/etc/cache/sman

function cache_man_txt () {
    if ! [[ -f "$smancache/$@.txt" ]]; then
        local tmpman="$(MANWIDTH=120 man $@)"

        if [ $? -eq 0 ]; then
            echo "Caching man page for $@."

            echo "$tmpman" | col -b > "$smancache/$@.txt"
        else
            return 1
        fi
    fi
}

function sman () {
    cache_man_txt $@

    if [ $? -eq 0 ]; then
        (
            chflags uchg "$smancache/$@.txt" &&

            subl -w "$smancache/$@.txt" &&

            chflags nouchg "$smancache/$@.txt" &
        ) &> /dev/null
    else
        return 1
    fi
}

function smandb () {
    if ! [[ -d $smancache ]]; then
        mkdir -p $smancache
    fi

    local manpages=$(man -k . | perl -pe 's/(.+) - .+/\1/' | perl -pe 's/\(.*?\)(?:, )?/\1\n/g' | egrep -v "^[[:space:]]*$")

    for i in $manpages; do
        cache_man_txt "$i" 2> /dev/null
    done
}
