#!/usr/bin/env sh

# Just a nice little alias so I can open chrome with switches easily
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

# Easy up to parent
alias ..='cd ..'

# ..x for going up x levels, up to 5
for i in {2..5}; do
    alias "..$i"="cd $(printf "../%.0s" $(seq 1 $i))"
done

# Easily reinstall my IE VMs if the trial period ends
alias getievms='curl -s https://raw.github.com/xdissent/ievms/master/ievms.sh | env INSTALL_PATH="$IEVMS_INSTALL_PATH" IEVMS_VERSIONS="8 9 10 11" bash'

# View recently created processes
alias rp="watch -n 0 -t 'ps -u "'$USER | tail -n $(tput lines) | cut -c1-$(tput cols)'"'"

# Sublime Text 3 subl alias
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# Easy alias for django-admin.py
alias dj='django-admin.py'

# Copy files to the pasteboard easily
alias pb='pbcopy < '

# Tools for opening files in different browsers
# Chrome
alias chr='open -a Google\ Chrome'

# Firefox
alias ffx='open -a Firefox'

# Safari
alias saf='open -a Safari'

# Opera
alias opr='open -a Opera'

# Fix tmux 256 colors
alias tmux='tmux -2'

# Keep the system alive and screen on.
alias stayup='caffeinate -dimsut 999999999999'

# Quick alias for git
alias g='git'

function build_git_aliases {
    local al
    local cm

    while read -r line; do
        al=$(echo $line | cut -d ' ' -f 1)
        cm=$(echo $line | cut -d ' ' -f 2-)

        if [[ ${cm:0:1} != '!' ]]; then
            cm="git $cm"
        else
            cm=$(echo $cm | sed -E 's/^! *//')
        fi

        if ! which $al &> /dev/null; then
          alias "g${al#alias.}"="$cm"
        fi
    done < <(git config --global --get-regexp '^alias\.')
}

build_git_aliases

function vim {
    if [[ -z $@ ]]; then
        $(which vim) .
    else
        $(which vim) $@
    fi
}

alias vi='vim'
