#!/usr/bin/env sh

# Just a nice little alias so I can open chrome with switches easily
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

# Easy up to parent
alias ..='cd ..'

# ..x for going up x levels, up to 5
for i in {2..5}; do
    alias "..$i"="cd $(printf "../%.0s" $(seq 1 $i))"
done

# Easily reinstall my IE VMs if the trial period ends
alias getievms='curl -s https://raw.github.com/xdissent/ievms/master/ievms.sh | env INSTALL_PATH="$IEVMS_INSTALL_PATH" IEVMS_VERSIONS="8 9 10 11" bash'

# View recently created processes
alias rp="watch -n 0 -t 'ps -u "'$USER | tail -n $(tput lines) | cut -c1-$(tput cols)'"'"

# Sublime Text 3 subl alias
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# Easy alias for django-admin.py
alias dj='django-admin.py'

# Copy files to the pasteboard easily
alias pb='pbcopy < '

# Tools for opening files in different browsers
# Chrome
alias chr='open -a Google\ Chrome'

# Firefox
alias ffx='open -a Firefox'

# Safari
alias saf='open -a Safari'

# Opera
alias opr='open -a Opera'
