#!/usr/bin/env bash

# function v(){
#     case $(echo $1 | tr 'A-Z' 'a-z') in
#         use)
#             source "$HOME/.virtualenv/envs/$2/bin/activate"
#             ;;
#         create)
#             if [[ "$(echo ${2:0:3})" = '-p=' ]]; then

#             fi

#             if ! [[ -d "$HOME/.virtualenv/envs/$2" ]]; then
#                 virtualenv "$HOME/.virtualenv/envs/$2"
#             else
#                 echo "$2 already exists."
#             fi

#             source "$HOME/.virtualenv/envs/$2/bin/activate"
#             ;;
#         *)
#             echo 'Usage:'
#             echo '    v use <env>'
#             echo '    v create <env> [<python>]'
#             ;;
#     esac
# }
