#!/usr/bin/env bash

hookpath=$(git config --get --path custom.globalhooks)

if [[ -d $hookpath ]]; then
    for hook in $hookpath/commit-msg/*; do
        if [[ -x $hook ]]; then
            $hook "$@"
        fi
    done
fi
